# Generated by Django 3.2.9 on 2021-11-10 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
                ('phone', models.IntegerField(max_length=13, validators=[django.core.validators.RegexValidator('^?=.*\\+[0-9]{3}\\s?[0-9]{2}\\s?[0-9]{3}\\s?[0-9]{4,5}$', 'пробелы разрешены, но не обязательны, как указано ниже +380 99 678 3498')])),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
