# Generated by Django 3.2.9 on 2021-11-10 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20211110_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^?=.*\\+[0-9]{3}\\s?[0-9]{2}\\s?[0-9]{3}\\s?[0-9]{4,5}$', 'пробелы разрешены, но не обязательны, как указано ниже +380 99 678 3498')]),
        ),
    ]
