# Generated by Django 3.2.9 on 2022-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
