# Generated by Django 3.2.9 on 2021-11-10 21:24

import bookingApps.utils.photo_utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]{,30}$', 'Country must be A-Z, a-z, max-length=30')])),
                ('city', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]{,30}$', 'City must be A-Z, a-z, max-length=30')])),
                ('region', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]{,30}$', 'Region must be A-Z, a-z, max-length=30')])),
                ('numbers_squares', models.IntegerField(validators=[django.core.validators.MinValueValidator(30, message='Numbers of squares must be min value 30')])),
                ('numbers_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Numbers of people must be min value 1')])),
                ('numbers_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Numbers of rooms must be min value 1')])),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'apartments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoRoomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=bookingApps.utils.photo_utils.PhotoRoomsUtils.upload_to)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_rooms', to='apartments.apartmentmodel')),
            ],
            options={
                'db_table': 'photo_rooms',
            },
        ),
    ]
