# Generated by Django 3.2.9 on 2021-11-10 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^?=.*\\+[0-9]{3}\\s?[0-9]{2}\\s?[0-9]{3}\\s?[0-9]{4,5}$', 'пробелы разрешены, но не обязательны, как указано ниже +380 99 678 3498')]),
        ),
    ]
