# Generated by Django 3.2.9 on 2021-12-08 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_apartment', '0003_auto_20211208_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsapartmentmodel',
            name='average_rating',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='commentsapartmentmodel',
            name='rating',
            field=models.FloatField(max_length=3, validators=[django.core.validators.MinValueValidator(1, 2), django.core.validators.MaxValueValidator(5, 2)]),
        ),
    ]
