# Generated by Django 3.2.9 on 2021-11-13 12:52

import bookingApps.utils.photo_utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0003_alter_apartmentmodel_user_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('rating', models.FloatField(max_length=3, validators=[django.core.validators.MinValueValidator(1, 3), django.core.validators.MaxValueValidator(5, 3)])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_apartment', to='apartments.apartmentmodel')),
            ],
            options={
                'db_table': 'comments_apartment',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=bookingApps.utils.photo_utils.PhotoCommentApartmentUtils.upload_to)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments_apartment', to='comments_apartment.commentsapartmentmodel')),
            ],
            options={
                'db_table': 'photo_comments_apartment',
            },
        ),
    ]
