# Generated by Django 3.2.9 on 2021-12-08 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_apartment', '0002_commentsapartmentmodel_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsapartmentmodel',
            name='average_rating',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='commentsapartmentmodel',
            name='rating',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
