# Generated by Django 3.2.9 on 2021-12-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_apartment', '0005_alter_commentsapartmentmodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsapartmentmodel',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='commentsapartmentmodel',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
