# Generated by Django 3.2.9 on 2022-01-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_apartment', '0007_commentsapartmentmodel_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsapartmentmodel',
            name='user_email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='commentsapartmentmodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
