# Generated by Django 3.2.9 on 2022-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateselectionmodel',
            name='name_user',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='dateselectionmodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dateselectionmodel',
            name='free_seats',
            field=models.BooleanField(default=False),
        ),
    ]
