# Generated by Django 3.2.9 on 2021-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_user', '0003_auto_20211217_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsusermodel',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
