# Generated by Django 3.2.9 on 2021-11-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0003_alter_apartmentmodel_user_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSelectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField()),
                ('date_departure', models.DateField()),
                ('number_days', models.IntegerField()),
                ('cost', models.FloatField()),
                ('free_seats', models.BooleanField(default=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_selection', to='apartments.apartmentmodel')),
            ],
            options={
                'db_table': 'date_selection',
                'ordering': ('id',),
            },
        ),
    ]
