# Generated by Django 3.2.9 on 2021-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_user', '0002_commentsusermodel_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsusermodel',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='commentsusermodel',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
