# Generated by Django 3.2.9 on 2021-12-31 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_user', '0004_commentsusermodel_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsusermodel',
            name='rating',
            field=models.FloatField(max_length=3, validators=[django.core.validators.MinValueValidator(1, 3), django.core.validators.MaxValueValidator(10, 3)]),
        ),
    ]
