# Generated by Django 3.2.9 on 2022-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_user', '0005_alter_commentsusermodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsusermodel',
            name='average_rating',
        ),
    ]
